version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=RABBIT_USER
      - RABBITMQ_DEFAULT_PASS=RABBIT_PASS
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data: