basePath: /api
info:
  contact: {}
  description: API desenvolvida para oferecer funcionalidades de criação, consulta,
    atualização e exclusão de produtos, com alertas via e-mail utilizando RabbitMQ.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Products CRUD API
  version: "1.0"
paths: {}
securityDefinitions:
  bearerAuth:
    description: Type "Bearer" followed by a space and a JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
